### ISSUE TITLE
Cuadro Comparativo - Método Científico 

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Daniel-Velasco-Lopez#1]
Daniel Velasco López
Actividad 3,  Cuadro Comparativo del Método Científico 

[METODO CIENTIFICO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-Daniel-Velasco-Lopez/files/9465278/METODO.CIENTIFICO.pdf)

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 3 CUADRO COMPARATIVO
DE 20% DE LA ACTIVIDAD OBTUVISTE 17.6 % DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
